apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vcontroller
  name: vcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcontroller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vcontroller
    spec:
      containers:
      - image: vidyablr/mcluster-valcontroller:0.1.0
        name: mcluster-valcontroller
        args:
        - --tls-cert-file=/var/run/webhook/serving-cert/tls.crt
        - --tls-private-key-file=/var/run/webhook/serving-cert/tls.key
        - --v=4
        resources: {}
        volumeMounts:
          - name: serving-cert
            mountPath: /var/run/webhook/serving-cert
      volumes:
        - name: serving-cert
          secret:
            secretName: certs
status: {}
