apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vcontroller
  name: vcontroller
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: vcontroller
status:
  loadBalancer: {}
